SapphireServer/Sapphire

src/servers/Server_Zone/ZoneMgr.cpp

Fixed by correcting the query that uses a older table name.

Fix zoneline

---

src/servers/Server_Common/ExdData.cpp
src/servers/Server_Common/ExdData.h
src/servers/Server_Zone/Item.cpp
src/servers/Server_Zone/Item.h
src/servers/Server_Zone/PacketHandlers.cpp
src/servers/Server_Zone/Player.cpp
src/servers/Server_Zone/PlayerEvent.cpp

Auto-attack was slightly off (attacking while unsheathed etc).
Worked on auto-attack damage as well.
Should fix an issue mentioned in #20 (MP regen), as well as calculating the correct refresh values for in and out of combat for HP, MP and TP.

Auto-attack adjustments (damage, behaviour), HP/MP/TP regen following new rules

---

bin/scripts/chai/skill/skillDef_3.chai
src/servers/Server_Common/ServerPacketDef.h
src/servers/Server_Zone/Actor.cpp
src/servers/Server_Zone/Actor.h
src/servers/Server_Zone/GameCommandHandler.cpp
src/servers/Server_Zone/StatusEffect.cpp
src/servers/Server_Zone/StatusEffect.h
src/servers/Server_Zone/StatusEffectContainer.cpp

We were reading power from the packet as a 32bit value, but apparently it's 2 values of 16-bit.
In the case of sprint, we gave it a value of "3791585310", which would then overflow (due to sign). 
The values now make a little more sense now that they're split.
The status function has also been extended further to allow the new param property.
Power parameter has been renamed as param, due to how other status may use this property not as a potency modifier but as a parameter for models, etc.
There are a few things that we learned from this, such as how the Transfiguration status works.
The first parameter (param) refers to the index found in transformation.exh, and applies scaling, speed and other properties (including UI as well) client-side. 
Curiously, some of the trial/raid boss models …

Sorted out power/param property of status (partially)

---

src/servers/Server_Zone/PacketHandlers.cpp

Fixed a Typo from HP GM Command saying TP was set Instead of HP

Fixed a Typo From HP Command saying TP Instead

---

src/servers/Server_Common/CMakeLists.txt
src/servers/Server_Lobby/CMakeLists.txt
src/servers/Server_Lobby/blowfish.cpp
src/servers/Server_REST/CMakeLists.txt
src/servers/Server_Zone/CMakeLists.txt

- Add /bigobj flag.
- Fix segfault while deriving a key for lobby encryption.
- GNU toolchain is not tested for 64bit. Use MSVC for now.
- Even with this PR, it's still quite a pain in the ass to build x64, basically you need to:
- Build 64bit version of boost and hope CMake can find them.
- Build 64bit version of zlib and MySQL connector(C version) lib and link against it.
- Also don't forget to copy 64bit version of dll to bin directory.
- Use Win64 version of generator **AND** force 64bit version of toolset.
- Oh, you forgot to clean CMakeCache and CMakeFiles sneak in somewhere? lol, go delete them first.
- Seriously, CMake, wth.
These step **should** be simplified in the future.

Initial attempt to fix 64bit build

---

src/servers/Server_Lobby/CMakeLists.txt
src/servers/Server_REST/CMakeLists.txt
src/servers/Server_Zone/CMakeLists.txt

This was done to reflect this PR: https://github.com/SapphireMordred/SapphireLibs/pull/6
After this PR, you'll only need to:
- Compile Boost with 64 bit
- Replace zlib and mysql dynamic library in ```bin``` directory with 64bit version.
[Already compiled for the test purpose.](https://github.com/SapphireMordred/Sapphire/files/1239213/lib.zip)
..to build for 64 bit.

Add 64bit lib linkage

---

src/servers/Server_REST/PlayerMinimal.cpp
src/servers/Server_REST/SapphireAPI.cpp
src/servers/Server_Zone/Actor/CalcBattle.cpp
src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp

Zone server would crash upon receiving an action interrupt if there was no active action.
This was made apparent by another issue (#68) in which the server received the action to cancel a cast, but no current action was instanced, which resulted in a crash.
Escaping character names on SQL queries so you can use single quotes in the character name field.
Further adjustments to the HP formula were made.

Fix action interrupt crash; Escaping character names; Adjustments to HP formula

---

CMakeSettings.json

VS2017.3 is shipped with CMake 3.8, which can't find a boost library properly. :<

Add Boost_COMPILER flag to CMakeSettings for VS

---

src/servers/Server_Common/Common.h
src/servers/Server_Common/Exd/ExdData.cpp
src/servers/Server_Common/Exd/ExdData.h
src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
src/servers/Server_Zone/Action/Action.cpp
src/servers/Server_Zone/Action/Action.h
src/servers/Server_Zone/Action/ActionCast.cpp
src/servers/Server_Zone/Action/ActionTeleport.cpp
src/servers/Server_Zone/Action/EventAction.cpp
src/servers/Server_Zone/Action/EventItemAction.cpp
src/servers/Server_Zone/Actor/Actor.cpp
src/servers/Server_Zone/Actor/Actor.h
src/servers/Server_Zone/Actor/Player.cpp
src/servers/Server_Zone/Actor/Player.h
src/servers/Server_Zone/Actor/PlayerInventory.cpp
src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
src/servers/Server_Zone/Network/Handlers/InventoryHandler.cpp
src/servers/Server_Zone/Network/PacketWrappers/PlayerSpawnPacket.h
src/servers/Server_Zone/StatusEffect/StatusEffectContainer.cpp
src/servers/Server_Zone/StatusEffect/StatusEffectContainer.h

Not much.
Definitions for presumably data for an action aspect, as well as an action's model. Open to ideas for better naming - was initially ActionType but that was already taken.
Handling removing status off from the HUD (aka "clicking" it off from the status bar) - this is defined as partial due to not handling which status effects are allowed to be removed (one could send in a packet that removes a poison status disguised for example).
Likely a boolean on one of the columns in the game's data.
There's also something weird going on between zoning. Seeing how our current status zoning implementation doesn't match retail (ie. doesn't stay between zones), leaving it at that.

Definition for ActionModel and ActionAspect; Handling removing status from HUD (partial);

---

src/servers/Server_Common/Network/PacketDef/Ipcs.h
src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h

RVA of opcode 0x6B is located at 0xB432E0 (4.06, post hotfix)
Note: This is zero sized. Client won't even pass a data pointer to the handler.

Add chat restricted packet def

---

scripts/chai/skill/cnj/skillDef_121.chai
scripts/chai/skill/cnj/skillDef_125.chai
scripts/chai/skill/cnj/skillDef_128.chai
scripts/chai/skill/cnj/skillDef_132.chai
scripts/chai/skill/skillDef_3.chai
src/servers/Server_Common/Common.h
src/servers/Server_Zone/Action/ActionCast.cpp
src/servers/Server_Zone/Actor/Actor.cpp
src/servers/Server_Zone/Actor/Actor.h
src/servers/Server_Zone/Actor/BattleNpc.cpp
src/servers/Server_Zone/Actor/CalcBattle.cpp
src/servers/Server_Zone/Actor/CalcBattle.h
src/servers/Server_Zone/Actor/Player.cpp
src/servers/Server_Zone/Actor/PlayerEvent.cpp
src/servers/Server_Zone/Actor/PlayerQuest.cpp
src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
src/servers/Server_Zone/Script/ScriptManager.cpp
src/servers/Server_Zone/ServerZone.cpp
src/servers/Server_Zone/StatusEffect/StatusEffectContainer.cpp
src/servers/Server_Zone/Zone/Zone.cpp

Added an actor pointer param to the status effect adding procedures, so that we know the source actor for the status effects.
Status effects inflicted on other actors should now be green, as well as other implications for status when they get scripted (cover, etc).
Still need to set up the proper aCtrl for cast finish, so that we can use the cast finish param (0x216, "You cast Cure.").
There also seems to be an odd behavior regarding packets being sent to other actors as well. Eg the cast cancel message doesn't really get sent to actors other than yourself.
Static cast galore.
Seems to take params that reads off the error message, another one for reading the levequest's name (from leve.exh) and possibly another for the actor's location (unsure on this one).

Status effect source reference; ActionCast battle log work; Cleaning compiler warnings up a bit;

---

scripts/chai/skill/cnj/skillDef_124.chai
scripts/chai/skill/cnj/skillDef_133.chai
src/servers/Server_Common/Common.h
src/servers/Server_Common/Exd/ExdData.cpp
src/servers/Server_Common/Exd/ExdData.h
src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
src/servers/Server_Zone/Action/ActionCast.cpp
src/servers/Server_Zone/Action/ActionTeleport.cpp
src/servers/Server_Zone/Actor/Actor.cpp
src/servers/Server_Zone/Actor/Player.cpp
src/servers/Server_Zone/Network/Handlers/SkillHandler.cpp

Work was done to define a few of the effect packet params.
Not much of interest, except for one (old unknown_5, now ValueModifier)
These mostly change the floating text and the info in the battelog.
- Value, being the number displayed in the floating text
- Effect Type, having many possible values (Damage, heal, MP gain/loss, TP gain/loss, etc)
- Hit severity, basically normal, crit, direct hit or directhitcrit. Also normal/crit are inverted values for heals
- Value Modifier, multiplies the Value param by 10 (need further research). Probably done due to int16_t limitations? The way I see it, any value bigger than 32767 should have this param set to 1. 
(Very) basic AoE heal handling. A bit off right now due to packets being misaligned with retail, but the logic is rudimentarily that.
Work …

Prototype AoE skill handling; Action Effect definitions and a bit of refactoring;

---

src/servers/Server_Common/Network/PacketDef/Ipcs.h
src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
src/servers/Server_Zone/Actor/Player.cpp
src/servers/Server_Zone/Actor/Player.h
src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp

FFXIV 4.06
Opcode ```1B4``` is handled at ```ffxiv.exe + 0xAC357C``` which saves first 8 bytes of message to engine global variable.
This value will be later on the game loop at ```ffxiv.exe + 0x5B9FE8``` which makes a call to ```ffxiv.exe + 0x47E0E0``` to get desired eorzean time as long as does game doesn't want to use a fixed time instead.
```@set eorzeatime value```
https://streamable.com/koi99
It's actually possible to replace ```@set eorzeatime``` command by ```//gm time value```
but then I'm too lazy to implement this so I'll dump this on to @AcedArmy

Offset eorzea time

---

src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
src/servers/Server_Zone/Action/ActionCast.cpp
src/servers/Server_Zone/Actor/Actor.cpp
src/servers/Server_Zone/Actor/Player.cpp
src/servers/Server_Zone/Actor/Player.h
src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
src/servers/Server_Zone/Network/PacketWrappers/PlayerSpawnPacket.h

Initial implementation of the title system. Shouldn't require much effort from here.
Moving forward from here:
* Implement title list. Add a method to player class that adds a title to the list, and then send the list to client when using the UI title select. Could do a few tests using a "!add title" command, and adding them through a random quest script.
* SQL. Fields for available title IDs, and current set title ID.
Fixes #70.
Wrong (Sapphire master 7abea43) - Notice max hp and hp values being inverted (and HP bar being displayed)
Correct
Relying on pPlayer->checkAction() to check if an action exists is a bad idea due to the second responsibility of updating the action that the method has. It'd return true as it initially existed, but midway through resolve the action pointer to a …

Player title prototype; Fix a few small issues;

---

src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h

In PacketHandlers.cpp ~line453 - we are trying to insert a hex value
(128) x80 and will cause an underflow to -128.  Suggestion is to move to
unsigned char to capture the intended value.
```
listPacket.data().entries[0].bytes[3] = 0x80; // 128
```

Potential Truncation - value over signed char

---

cmake/compiler.cmake

- /ZI is not a link flag
- /ZI is not settable via CMAKE_CXX_FLAGS
- /Zi is default unless add_defitions(/ZI)
- Need to disable SAFESEH before /ZI

 Correctly applying /ZI for debug

---

src/servers/Server_REST/main.cpp
src/tools/exd_common_gen/CMakeLists.txt

- std::equal can take a 2nd iterator end
- use _SCL_SECURE_NO_WARNINGS for std::copy issues in exd_common_gen

Addressing unchecked iterator issues with core project

---

src/servers/Server_REST/CMakeLists.txt

- couldnt't find a better way to find the subpath or a root
- can't pass other iter length or it fails to view them as main and
subdir

Silence unchecked iterators for server_rest

---

README.md
src/servers/Server_Common/CommonGen.cpp
src/servers/Server_Common/CommonGen.h
src/servers/Server_REST/PlayerMinimal.cpp
src/servers/Server_Zone/StatusEffect/StatusEffectContainer.cpp
src/tools/exd_common_gen/generated.h
src/tools/exd_common_gen/main.cpp

Include stdint.h so we can have the type aliases needed (mostly uint8_t)
None of the tools in this repository depend on a C# runtime.

Fix generated enum build break; Remove Mono as dependency from README;

---

cmake/mysql.cmake

This should make building on mac and non-Ubuntu linux distros easier. Also works with custom MySQL builds/installs.

Fix CMake MySQL module to be more nix-friendly

---

.gitignore
.travis.yml

Setup a proper build matrix. Dependencies of the buildchain vs the build itself are split up; more stuff in parallel should be faster.
I'd like to not need the extra compiler installs at all but Travis uses 14.04 which is almost 4 years old and somewhat out of date so we need something more modern for C++11/14/17 support according to Travis docs. This may not actually be the case but someone would need to check which features we user and if the default `g++` supports them.
The `software-properties-common` dependency isn't really needed unless I've missed one of the tools. CMake was removed as a dependency since Trusty comes with 3.2 and our update only installs 3.5, while the project minimum is 2.6 currently and aim to upgrade to 3.1.
Add support for mtime_cache, a small Ruby gem for …

Update Travis config for faster builds

---

sql/import.bat

Script based off the import.sql from FFXIV Classic. Uses Windows-friendly batch scripting and paths so users can just adjust the file to their environment and run to import/reimport a fresh database. It will always run the update.sql file last to prevent any conflicts while importing.

Add a more windows-friendly SQL import script

---

CMakeSettings.json

People are asking for help in `#troubleshooting` every other day for CMake issues in VS2017. This PR adds a generator definition with a slightly bumped compiler version for Boost so there should be no more need for silly CLI flags or other workarounds. Built-in CMake should work just fine too. Tested by @GokuWeedLord.

Add VS2017 generator definitions

---

src/servers/Server_Zone/Inventory/Inventory.cpp

should always be divided by 13 instead of 12
6 armour slots + 5 accessory slots + 2 weapon slots - weapon is counted twice in the event that a 2 handed weapon is equipped

fix itemlevel calculation being incorrect

---

src/servers/Server_Common/Network/GamePacket.h
src/servers/Server_Zone/Network/Handlers/PacketHandlers.cpp

I falsely assumed that [getDataAt](https://github.com/perize/Sapphire/blob/0fa3f93ce901ca59fb26fc94ae6f1652c16996ea/src/servers/Server_Common/Network/GamePacket.h#L46) would return a value which I could just cast it to the pointer to get an address of the packet data.
But nope, @itsMaru pointed out that perform does not work on Sapphire and sends some uninitialized memory.
Client sent:
Response, note that 0xCC is not supposed to be happen here.
This PR fix should fix it.

Perform fix

---

src/servers/sapphire_api/PlayerMinimal.h
src/servers/sapphire_zone/Actor/Player.cpp
src/servers/sapphire_zone/Actor/Player.h
src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.cpp
src/servers/sapphire_zone/Network/Handlers/GMCommandHandlers.cpp
src/servers/sapphire_zone/Network/Handlers/PacketHandlers.cpp
src/servers/sapphire_zone/Network/PacketWrappers/PlayerSpawnPacket.h

- Added the GM Icons and a few others I was messing with to the OnlineStatusMask. (there should be a better way to do it but it should be good for now)
- Added the GM Invis command. I most likely did this in the most shit way possible but non the less it works.
- Added GM Chat Types. These where only added for the existing types. (shout, yell, say). If the player is a GM rank of any kind it will override the existing type with the GM variant.

Added a whole lot of GM Stuff

---

src/common/Network/PacketDef/Ipcs.h
src/servers/sapphire_lobby/GameConnection.cpp

Done by @Minoost and @SapphireMordred , just reflecting what was researched
The opcode shifts are mostly from #296
Here are a few things to note:
Zone will crash on start-up due to aetheryte field for Territory.
Fix by replacing the field getter for something else (eg. 0) for now until it is resolved for the autogenerated file
(src/common/Exd/ExdDataGenerated.cpp, line 1677)
Client will crash on character list due to the JSON payload changing (more specifically when the list has entries). Loading from an account with no characters created will allow the client to proceed through.
Zone loading will not finish, unfortunately.
(reminder to look at PlayerSpawn uninitialized memory later on)

4.3 opcode shift+lobby versioning

---

CMakeLists.txt
CMakeSettings.json

our boost cmake module used variables that were not set beforehand, plus our boost version only supplied static libs for vc140 toolkit and thus could not find them due to naming
a suggestion would be checking on our cmake boost module to check if the variable was set, and warn beforehand

Fix boost static lib cmake find (experimental)

---

src/common/Forwards.h
src/common/Network/GamePacketNew.h
src/common/Network/PacketContainer.cpp
src/common/Network/PacketContainer.h
src/servers/sapphire_zone/Network/GameConnection.cpp

vector in PacketContainer was handling base packet type, thus slicing down any derived object to the base.
handling packets in the container and dereferencing them calls the correct derived functions in the vtable
though, we may want to rethink our container if the pointer not being there was thought of and was intended

Fix packet object slicing;

---

src/common/Network/PacketDef/Chat/ServerChatDef.h
src/servers/sapphire_zone/Network/Handlers/PacketHandlers.cpp

- Fixed tells not working by changing the location we look in the packet for the playername and message
- I also noticed if you set u3b to 1 it marks the tell as a gm tell but only set to 1 from my little testing

Fixed Tell and add research I found for u3b in tell struct

---

src/servers/sapphire_zone/Actor/Chara.cpp

This fixes the target of selected players appearing as "???" until they target something for themselves

Correctly initialize m_targetId in Chara

---

src/common/Network/PacketDef/Zone/ServerZoneDef.h
src/servers/sapphire_zone/Actor/Player.cpp
src/servers/sapphire_zone/Network/PacketWrappers/InitUIPacket.h

InitUI now has pose (and weaponPose) defined, and is being set (meaning that pose now persists through logins).
More research on ``unknownMask5C4`` could certainly be interesting, as they were grouped together. It is not immediatly obvious as to what the values mean however.

InitUI pose def + set val;

---

README.md
src/servers/Scripts/opening/OpeningGridania.cpp
src/servers/Scripts/opening/OpeningLimsa.cpp
src/servers/Scripts/opening/OpeningUldah.cpp
src/servers/sapphire_api/PlayerMinimal.cpp
src/servers/sapphire_api/PlayerMinimal.h

Creating a new character will replicate retail in adding accessories.
Additionally, it'll add the proper item from the choice in the cutscene.
Currently there's an issue with the item handling process. As such the ring gained from the cutscene will not be equipped automatically. This is to be fixed on dependency of item handling

Opening + char create items (fixes #356)

---

src/common/Network/PacketDef/Zone/ServerZoneDef.h

Sitting Cpose is still broken, check #391 for more info

Fixed OnlineStatus and Standing Cpose in PlayerSpawn

---

src/common/Network/PacketDef/Zone/ServerZoneDef.h
src/servers/sapphire_zone/Network/PacketWrappers/ModelEquipPacket.h

Turns out padding1 holds some extra stuff which include the current class id and level
- Added them to the ModelEquip def

ModelEquip Updates

---

src/servers/Scripts/quest/ManFst004.cpp

The function setZone caused a client crash with call.
Changed with forceZoneing and now the quest work properly! :smile:

Want to avoid a client crash on ManFst004

---

cmake/compiler.cmake

At my second time with this problem I found the reason that VS didn't let me compile build.
For some weird reason, Cmake did a build with standard std::c++14 (And Im full able to use std::c++17).

Avoid Cmake that create C++14 build with C++17 installed

---

src/common/Network/GamePacketNew.h
src/common/Util/Util.cpp
src/common/Util/Util.h
src/world/Actor/Player.cpp
src/world/Manager/MarketMgr.cpp
src/world/Manager/RNGMgr.cpp
src/world/Manager/RNGMgr.h
src/world/Network/GameConnection.cpp
src/world/Network/Handlers/PacketHandlers.cpp
src/world/ServerMgr.cpp
src/world/Session.cpp
src/world/Session.h
src/world/Territory/Housing/HousingInteriorTerritory.cpp
src/world/Territory/Land.cpp
src/world/Territory/Zone.cpp

Concept of a manager that can handle our RNG needs. Currently can only use one engine (std::mt19937), and can't be swapped on runtime.
Will be adding more stuff in the future (single number without having to pull a new generator, maybe more engine choices and swapping between them, and others).
Code also needs a clean up - the seed generation is duplicated, however the plan is to not have two separate engines (one for manager and other for the generator object), but have the manager own its own generator object. This is noted and will be done soon
Our getTimeSeconds returned an int64, and thus we had to use static_cast down to uint32_t on a number of cases.

RNGManager PoC

---

src/common/Network/CommonActorControl.h
src/common/Network/PacketDef/Ipcs.h
src/common/Network/PacketDef/Zone/ServerZoneDef.h
src/world/Network/PacketWrappers/ExaminePacket.h
src/world/Network/PacketWrappers/PlayerSpawnPacket.h

Adding the worldId to Examine fixed the World Name appearing as "Unknown" when examining a player.
Adding it to PlayerSpawn fixed the World Name not showing up in the HUD, and fixed right-clicking a player to send a /tell.

ActorControl, OpCode and NpcSpawn findings. Also added worldId to Examine and PlayerSpawn

---

src/common/Common.h
src/common/Network/PacketDef/Ipcs.h
src/common/Network/PacketDef/Zone/ServerZoneDef.h

Correction of https://github.com/SapphireServer/Sapphire/pull/571.
I believe everything is in order, this time? I also renamed a couple `unknown` properties in PlayerStats to CP and GP, after a bit of extra testing.
Also, I'm not sure if this is intentional, but `Common::CLASSJOB_SLOTS` is 28, when there are 38 classes and jobs in total. https://github.com/SapphireServer/Sapphire/commit/b0eba69733425103e0d2fb4719a00c013686a0d0 has all of them and their IDs, but I collapsed them into an array in https://github.com/SapphireServer/Sapphire/commit/fbf82c937e991659d56782a8491a913c68249d80.

Added ExamineSearchInfo opcode and packet structure, ID'd CP and GP in PlayerStats packet structure

---

src/common/Network/PacketDef/Ipcs.h
src/common/Network/PacketDef/Zone/ServerZoneDef.h

The structs in ServerZoneDef didn't match Ipcs.h and everything else did :v There was also a typo in there.
As for the MarketBoardItemListing struct, the reason for the nested `unknown2` struct being looped is because it always contains the same data 1-3 times.

MarketBoardItemListing updated opcode, reordered ServerZoneDef market structs

---

src/world/Actor/PlayerQuest.cpp

Quest scripts need to call player.giveQuestRewards( getId(), result.param3 ) for it to work.

Fix quest reward choice.

---

src/api/SapphireApi.cpp

Not all data was deleted when deleting a character, making it impossible to play a new character with the same name. Add in delete commands for the additional tables and remove the reference to the (non-existent) `charainfofriendlist` table.

Update deleteCharacter, remove charainfofriendlist

---

src/common/Network/PacketDef/Zone/ServerZoneDef.h

I didn't bother trying to fix those offset values in the names of unknown fields. At this point this packet is just so broken. Well at least I tried to line up important stuff like levels, exp and player name.

Solve the mystery of second quest not showing in gridania or limsa.

---

src/tools/quest_parser/main.cpp

Use correct method of determining actor, use callback variables instead of inline functions within scenes, and use the correct namespace.

quest_parser template update

---

src/tools/quest_parser/main.cpp

The generated onBNpcKill and onEObjHit functions were using the wrong case for the constants they used. Ensure that they use the same case as the declared constants, and reduce duplicate code.
Also, fix a typo in the onEObjHit function prototype which was causing generated scripts to not compile properly, and revert the incorrect addition (by me in an earlier commit) of "override".

quest_parser: Fix case for constants

---

src/world/Actor/Player.h
src/world/Actor/PlayerQuest.cpp

It's currently impossible to permanently store quest completion flags for quests beyond questId 2047 (67583) due to the code using a type that's too small. This manifests in the correct quest completion packet being sent, but as soon as you move to another zone the quest disappears from the journal (and is probably replaced by another quest you didn't ask for).
This fixes the issue by using an appropriately-sized index variable, and also increases the flag storage so that all currently-available quests can be stored.

Fix quest completion for questId > 2047 (67583)

---

src/world/Actor/Player.cpp
src/world/Actor/Player.h
src/world/Actor/PlayerInventory.cpp
src/world/Actor/PlayerSql.cpp

1. Adding multiple items in a loop sometimes get duplicated primary key error due to async item db insert.
2. Temperate item being written into db.
3. mergeItem leaving ghost item in the container.

Fix 3 inventory issues.

---

src/common/Network/PacketDef/Ipcs.h

The number format here was typoed, preventing a successful compile.

Fix bad hex number

---

src/common/Exd/ExdDataGenerated.cpp
src/common/Exd/ExdDataGenerated.h
src/common/Network/CommonActorControl.h
src/common/Network/PacketDef/Ipcs.h
src/common/Network/PacketDef/Zone/ServerZoneDef.h
src/common/Util/Util.cpp
src/world/Actor/Player.cpp
src/world/Actor/Player.h
src/world/Actor/PlayerInventory.cpp
src/world/Actor/PlayerQuest.cpp
src/world/Event/EventHandler.h
src/world/Manager/MapMgr.cpp
src/world/Manager/MapMgr.h
src/world/Script/NativeScriptApi.cpp
src/world/Script/NativeScriptApi.h
src/world/ServerMgr.cpp
src/world/Territory/InstanceObjectCache.cpp
src/world/Territory/InstanceObjectCache.h

I have wrote a map manager that manages the map icons for the big map.
It is supporting the following map icons for now:
- Quest icons (only pre-accepted ones, because accepted ones are getting handled by the client)
- Guildleve icons
- Guildhest icons
- Beginner arena icons
- Triple Triad Master npc icon
For the quest icons I reversed engineered the quest availability check from the client. It doesn't check everything what the client does for now, but all that what is currently supported by the server.

Including support for basic map icons

---

src/common/Network/PacketDef/Ipcs.h
src/common/Network/PacketDef/Zone/ClientZoneDef.h
src/world/Network/GameConnection.cpp

This should fix the Duty Finder and update the opcodes for the newest client.
The opcode updates are courtesy of collett, Flavien Normand and Taezen.
I had assistance with CFCommenceHandler from Mordred and collett.

Update opcodes for 5.58 hotfix and fix CFCommenceHandler

---

src/world/Action/Action.cpp
src/world/Action/EffectBuilder.cpp
src/world/Action/EffectBuilder.h
src/world/Action/ItemAction.cpp
src/world/Action/MountAction.cpp
src/world/Actor/Chara.cpp
src/world/Manager/DebugCommandMgr.cpp
src/world/Network/PacketWrappers/EffectPacket.h
src/world/Network/PacketWrappers/EffectPacket1.h

AoE packets are not fully tested (only on single targets)
currently sheets are broken so combos are forced on, and left for the client to decide (ComboContinue, some canSelfTarget tests)
comparison for EffectPacket1 vs EffectPacket:

[3.0] action combo work; add support for multiple action ct/tg; fix effectpacket inconsistencies; fix infinite loop on aoe no target;

---

src/world/Actor/PlayerQuest.cpp

Thanks to the recomplete feature of the FFXV event, we finally know how to remove completed quest properly.

Remove completed quest properly

---

src/scripts/quest/classquest/ARC/ClsArc004.cpp

Invalid bit flags were the cause of nothing being able to talk to that NPC during Seq5.

[3.0] Fix ClsArc004

---

src/tools/quest_parser/CMakeLists.txt
src/tools/quest_parser/main.cpp

Less hardcoded values and cmake will now copy the unluac .jar file to the build directory.

[3.x] Clean up quest_parser

---

src/scripts/quest/classquest/CNJ/ClsCnj001.cpp
src/scripts/quest/classquest/CNJ/ClsCnj002.cpp
src/scripts/quest/classquest/CNJ/ClsCnj003.cpp
src/scripts/quest/classquest/CNJ/ClsCnj004.cpp
src/scripts/quest/classquest/CNJ/ClsCnj006.cpp
src/world/Actor/BNpc.cpp
src/world/Actor/BNpc.h
src/world/Task/DelayedEmnityTask.cpp
src/world/Task/DelayedEmnityTask.h

Add a task that delays adding the player to a BNpc's hate list, so that we can be the same as retail for quests that interacting with an EObj spawns BNpcs.

[3.0] DelayedEmnityTask and BNpc additions

---

src/world/Manager/DebugCommandMgr.cpp
src/world/Manager/DebugCommandMgr.h

Adds the command `!ew`, which takes a predefined list of possible locations to warp to.  
Example usage: `!ew waking_sands`

[3.0] Add easyWarp Debug Command

---

src/world/Network/Handlers/GMCommandHandlers.cpp

ignore branch name, i was looking into mariadb 11 again

[3.x] fix warpmgr argument on no aetherytes/teleport found;

---

src/world/Manager/TerritoryMgr.cpp

Used for places like The Howling Eye entrance during MSQ. Can see other players here so it should be default.

[3.0] Add BeforeTrialDung to isDefaultTerritory

---

src/common/Service.cpp
src/common/Service.h
src/scripts/ScriptLoader.cpp.in
src/world/Script/ScriptLoader.cpp
src/world/mainGameServer.cpp

After some peeking into 3.x I think I'd just use this old workaround.
Slightly slower since a map lookup is introduced, but no need to add services one by one when they are found crashing.

Service locator workaround for Visual Studio.

---

src/scripts/quest/subquest/limsa/SubSea002.cpp
src/scripts/quest/subquest/limsa/SubSea003.cpp
src/scripts/quest/subquest/limsa/SubSea004.cpp
src/scripts/quest/subquest/limsa/SubSea005.cpp
src/scripts/quest/subquest/limsa/SubSea007.cpp
src/scripts/quest/subquest/limsa/SubSea008.cpp
src/scripts/quest/subquest/limsa/SubSea009.cpp
src/scripts/quest/subquest/limsa/SubSea011.cpp
src/scripts/quest/subquest/limsa/SubSea012.cpp
src/scripts/quest/subquest/limsa/SubSea013.cpp
src/scripts/quest/subquest/limsa/SubSea014.cpp
src/scripts/quest/subquest/limsa/SubSea015.cpp
src/scripts/quest/subquest/limsa/SubSea016.cpp

Implemented:
- SubSea002 - Suspiciously Sober
- SubSea003 - Proper Procedure
- SubSea004 - The Right Price
- SubSea005 - Duty Calls
- SubSea007 - A Thousand Words
- SubSea008 - Licensed To Reave
- SubSea009 - Lost and Found
- SubSea011 - Back in the Water
- SubSea013 - The Rats in the Wharf
- SubSea014 - Soothing the Savage Siren
- SubSea015 - Fool Me Once
- SubSea016 - Edelweiss, Edelweiss
Updated:
- SubSea012 - Glory Days
> Fixed Enemy0 Id and added EventNotices for onBNpcKill and onTalk

Implemented more Limsa Sidequests

---

src/scripts/quest/ManSea003.cpp
src/scripts/quest/ManWil003.cpp
src/scripts/quest/subquest/limsa/SubSea003.cpp
src/scripts/quest/subquest/limsa/SubSea004.cpp
src/scripts/quest/subquest/limsa/SubSea005.cpp
src/scripts/quest/subquest/limsa/SubSea007.cpp
src/scripts/quest/subquest/limsa/SubSea008.cpp
src/scripts/quest/subquest/limsa/SubSea011.cpp
src/scripts/quest/subquest/limsa/SubSea013.cpp
src/scripts/quest/subquest/limsa/SubSea014.cpp
src/scripts/quest/subquest/limsa/SubSea015.cpp
src/scripts/quest/subquest/limsa/SubSea016.cpp

Lambda functions for the Pugilist and Arcanist versions of Close To Home (ManWil003 + ManSea003) wasn't being run, making it so you couldn't take/progress those quests. 
Works with new quest parser template so I just updated it.

Fixed lambda functions not running during some starting quests and added HIDE_HOTBAR to some Limsa sidequests

---

deps/datReader/DatCategories/bg/lgb.h
deps/datReader/Exd.cpp
deps/datReader/Exd.h
src/common/Exd/ExdData.h
src/tools/action_parse/main.cpp
src/tools/wiki_parse/main.cpp
src/world/ContentFinder/ContentFinder.cpp
src/world/Manager/AchievementMgr.cpp
src/world/Manager/MapMgr.cpp
src/world/Manager/ShopMgr.cpp
src/world/Manager/TerritoryMgr.cpp
src/world/Network/Handlers/CFHandlers.cpp
src/world/Network/Handlers/GMCommandHandlers.cpp
src/world/Network/Util/PacketUtil.cpp
src/world/Territory/InstanceObjectCache.cpp

45s -> 28s (37%) to start world server up on debug (5900x)
getRows should be used instead of getIdList then looping through the list to manually get the exd data.
I've gone through and replaced most of the getIdList calls on the project.
example:
```cpp
auto contentListIds = exdData.getIdList< Excel::InstanceContent >();
for( auto id : contentListIds )
{
auto instanceContent = exdData.getRow< Excel::InstanceContent >( id );
if( instanceContent->data().TerritoryType == territoryTypeId )
{
return id;
}
}
```
should now be:
```cpp
auto contentFinderList = exdData.getRows< Excel::InstanceContent >();
for( const auto& [ id, instanceContent ] : contentFinderList )
{
if( instanceContent->data().TerritoryType == territoryTypeId )
{
return id;
}
}
```

[3.x] overall optimizations; add getRows to exd data;

---

src/scripts/instances/questbattles/UnderneaththeSultantree.cpp
src/scripts/quest/ManWil005.cpp
src/scripts/quest/classquest/MIN/ClsMin502.cpp
src/scripts/quest/classquest/MIN/ClsMin580.cpp
src/scripts/quest/classquest/MIN/ClsMin600.cpp
src/scripts/quest/classquest/WHM/JobWhm001.cpp
src/scripts/quest/classquest/WHM/JobWhm450.cpp
src/scripts/quest/subquest/blackshroud_central/SubFst033.cpp
src/scripts/quest/subquest/blackshroud_central/SubFst052.cpp
src/scripts/quest/subquest/blackshroud_central/SubFst067.cpp
src/scripts/quest/subquest/blackshroud_central/SubFst069.cpp
src/scripts/quest/subquest/blackshroud_north/GaiUsa803.cpp
src/scripts/quest/subquest/coerthas_central/GaiUsb808.cpp
src/scripts/quest/subquest/gridania/GaiUsc609.cpp
src/scripts/quest/subquest/lanoscea_outer/GaiUsb406.cpp
src/scripts/quest/subquest/limsa/SubSea002.cpp
src/scripts/quest/subquest/limsa/SubSea004.cpp
src/scripts/quest/subquest/limsa/SubSea007.cpp
src/scripts/quest/subquest/limsa/SubSea008.cpp
src/scripts/quest/subquest/limsa/SubSea016.cpp
src/scripts/quest/subquest/thanalan_central/SubWil025.cpp
src/scripts/quest/subquest/thanalan_central/SubWil026.cpp
src/scripts/quest/subquest/thanalan_central/SubWil060.cpp
src/scripts/quest/subquest/thanalan_central/SubWil062.cpp
src/scripts/quest/subquest/thanalan_central/SubWil063.cpp
src/scripts/quest/subquest/thanalan_central/SubWil064.cpp
src/scripts/quest/subquest/thanalan_central/SubWil070.cpp
src/scripts/quest/subquest/thanalan_central/SubWil073.cpp
src/scripts/quest/subquest/thanalan_central/SubWil080.cpp

Implemented ManWil005 and the quest battle that goes with it (Underneath the Sultantree)
Added Item Icons to all quests that had notices with a TODO for item icons marked beside them.
Implemented more SubWil quests (Ul'dah MSQ)
- SubWil025
- SubWil026
- SubWil060
- SubWil062
- SubWil063
- Subwil064
- SubWil070
- SubWil073
- SubWil080
and some minor side quest fixes (SubSea) with setting BitFlag8

SubWil/ManWil MSQ and adding Item Icons to quest notices

---

src/common/Network/PacketDef/Ipcs.h

Fixed `PlaceFieldMarker`, `PlaceFieldMarkerPreset`, `IslandWorkshopSupplyDemand` before applying the diff.
I wasn't able to fix the ClientZone ones beyond what was already found for 6.40, but there doesn't appear to be many recent ones anyways.

Updates for patch 6.40h

---

src/common/Common.h
src/world/Action/ItemAction.cpp
src/world/Action/ItemAction.h
src/world/Actor/Player.cpp

- Added missing `handleSongItem` item action. The function to register an orchestrion roll was already implemented in Player.cpp but was just missing the handler function.
- Added additional condition to allow for currently equipped title to be removed. titleID = 0 corresponds to the "None" entry in the title selection menu, all players already have this

Minor ItemAction and Player Title fixes

---

src/common/Common.h
src/scripts/action/common/ActionTeleport5.cpp
src/scripts/common/aethernet/Aetheryte.cpp
src/world/Actor/Player.cpp
src/world/Actor/Player.h
src/world/Network/Handlers/PacketCommandHandler.cpp

Also fix issue on Aetheryte menu where housing option was being treated as set homepoint

Implement Aetheryte Tickets

---

deps/datReader/Exd/Structs.h
src/scripts/statuseffect/StatusEffectDefiance.cpp
src/tools/action_parse/main.cpp
src/world/Action/Action.cpp
src/world/Action/ActionLut.h
src/world/Action/ActionResult.cpp
src/world/Action/ActionResult.h
src/world/Action/ActionResultBuilder.cpp
src/world/Action/ActionResultBuilder.h
src/world/Actor/Chara.cpp
src/world/Actor/Chara.h
src/world/StatusEffect/StatusEffect.cpp
src/world/StatusEffect/StatusEffect.h

Should resolve the comments made in #958 for the most part.

[3.x] WIP: Cleanup of initial action implementation

---

src/world/Action/ActionResultBuilder.cpp
src/world/Actor/Player.cpp
src/world/Actor/Player.h
src/world/Manager/DebugCommandMgr.cpp
src/world/Manager/MapMgr.cpp
src/world/Manager/MapMgr.h
src/world/Network/Handlers/GMCommandHandlers.cpp

i have half a mind to load the entire 0a exd into memory. someone talk me out of it

[3.x] cache eobj/enpc exd; fix server crash on aoe skills; !add unlockall (0xff unlock bitmask);

---

src/world/AI/Fsm/StateCombat.cpp
src/world/Actor/BNpc.cpp
src/world/Actor/BNpc.h

Striking dummies (and all other immobile entities) will now deaggro when moving more than 30 units away (instead of never).
I don't know which distance they used in retail during HW but the current live version has a significantly increased deaggro distance for dummies since they added a reset aggro context menu. So I used 30y> because it's longer than all player attacks.

Dummy aggro fix

---

src/world/Actor/Player.h
src/world/Actor/PlayerQuest.cpp
src/world/Manager/QuestMgr.cpp
src/world/Manager/QuestMgr.h

This function provides the EventItem icon, which can then be used by the sendNotice function in quests.
Example:
`static constexpr auto Item0 = 2000148;`
`eventMgr().sendNotice( player, getId(), 0, { quest.getUI8AH(), 3, player.getQuestItemIcon( Item0 ) } );`

getEventItemIcon function 

---

deps/datReader/Exd.h
deps/datReader/ExdCat.cpp
deps/datReader/ExdCat.h
deps/datReader/ExdData.cpp
deps/datReader/ExdData.h
src/common/Exd/ExdData.h
src/tools/nav_export/main.cpp
src/tools/pcb_reader/main.cpp
src/world/WorldServer.cpp

Before:
After:
Every call to `getRow` would copy all data of that category and then immediately destruct it again, causing tons of allocations/deallocations.

World initialization performance

---

cmake/FindMySQL.cmake

On Linux/macos there are no changes.
This was after a discussion with Malek Bael who found that an old MySQL version would be detected. I changed the algorithm to prioritize MariaDB over MySQL and pick the newest version. You can specify `-DMYSQL_ROOT=xxx` to force a specific MySQL version too (or set an environment variable with the same name).

Rewrite MySQL find algorithm on Windows

---

src/world/Manager/RNGMgr.h

I forgot to add this when I made RNGMgr years ago.
Quality of RNG is worsened when set (so don't), but this is for testing distribution programmatically (as in within the same scope of the seed set).
Since Sapphire uses RNG in a bunch of places, this will not guarantee your RNG output is always the same. As soon as this call leaves scope you're on your own
More on code docs.

[3.x] Add debug manual seeding to RNGMgr;

---

src/world/Action/Job/Warrior.cpp

This PR makes it so that the parry bonus is the intended 2, 4, 6, 8, 10 instead of effectively capping out at 4.

Fix parry bonus for WAR wrath
