- src/servers/Server_Zone/GameCommandHandler.cpp
Table was renamed from dbdiscoveryref to discoveryinfo, updating to reflect that.
> Updated table name in 'discovery_pos'

- src/servers/Server_REST/main.cpp
- src/servers/Server_Zone/ServerZone.cpp
Updated REST and Zone server to use log folder.
> Standardize log location

- .appveyor.yml
need to set up the project on appveyor, grab badge from settings > badges
> add appveyor test

- src/servers/Server_Common/ServerPacketDef.h
- src/servers/Server_Zone/GameConnection.cpp
- src/servers/Server_Zone/GameConnection.h
- src/servers/Server_Zone/PacketHandlers.cpp
> Implement basic duty finder window response

- CMakeSettings.json
See titles.
This PR also fix nested indent (2 and 4) to 2.
> Change buildroot to fix CMake error after VS2017.3 update

- .gitignore
This is tempoary though, scripts and config directory should be seperated from bin directory. (Eventually)
> Exclude script directory from ignoring

- scripts/chai/skill/cnj/skillDef_121.chai
- scripts/chai/skill/cnj/skillDef_125.chai
- scripts/chai/skill/cnj/skillDef_132.chai
- scripts/chai/status/statusDef_143.chai
- scripts/chai/status/statusDef_144.chai
- src/servers/Server_Common/Common.h
- src/servers/Server_Common/Util/UtilMath.cpp
- src/servers/Server_Zone/Action/ActionCast.cpp
- src/servers/Server_Zone/Actor/Actor.cpp
- src/servers/Server_Zone/Actor/BattleNpc.cpp
- src/servers/Server_Zone/Actor/CalcBattle.cpp
- src/servers/Server_Zone/Actor/Player.cpp
- src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
- src/servers/Server_Zone/StatusEffect/StatusEffectContainer.cpp
Very small changes. 
- Seeing if I can get raising stuff going, but right now I'll just get the base up for now (seeing how my current impl is hackish and not proper)
- Fixed issue #68 
- Partially stop skills from affecting dead actors
- Cast bar on the target bar takes values in seconds (not ms as it was before).
> Fix build; Fix issue #68; Base raise handling; Sorting out action casting stuff;

- scripts/chai/aetheryte/Aetheryte.chai
- sql/zonepositions.sql
Added all the Positions of Ul'dah's Aethernet and Removed setTeleporting line of code from the Aetheryte script
> Ul'dah Aethernet and setTeleporting Removed

- src/servers/Server_Lobby/CMakeLists.txt
- src/servers/Server_REST/CMakeLists.txt
- src/servers/Server_Zone/CMakeLists.txt
- usage: tools > options > debugging > general > enable edit and continue (tick all options within its subtree)
- attach vs to a server, edit its code, alt + f10
> enabled edit and continue on windows

- src/servers/Server_Zone/Actor/CalcBattle.cpp
Further alignment with retail for baseStat. HW and SB are ok, ARR has off by ones.
> New BaseStat formulas (SB, HW, ARR)

- .travis.yml
- src/servers/Server_REST/CMakeLists.txt
- src/servers/Server_REST/SapphireAPI.cpp
- src/servers/Server_REST/main.cpp
> First attempt to use Argon2 to encrypt password

- src/tools/Script/ce_dump_vfs_path_406.lua
Requested to port a script for 4.06 from the Discord channel.
ASM signature is included for future patches.
> Ported dump vfs path script to 4.06

- .appveyor.yml
- CMakeLists.txt
- cmake/FindMySQLConnectorCPP.cmake
- cmake/compiler.cmake
- fixed edit and continue being disabled (-DCMAKE_BUILD_TYPE="Debug" to enable)
> fixed search paths for mysql cpp connector

- src/servers/Server_Common/Common.h
> Add SetOwnerId def

- src/servers/Server_Common/Database/Database.h
- src/servers/Server_REST/PlayerMinimal.cpp
- src/servers/Server_REST/SapphireAPI.cpp
- src/servers/Server_Zone/Actor/PlayerSql.cpp
- src/servers/Server_Zone/Inventory/Inventory.cpp
Fixed the ContentID problem, This is a fix until the new db stuff
> Fixed the Lobby ContentID Problem

- sql/zonepositions.sql
Added all of the Aethernet and Zoning positions to Idyllshire, so walking through zones to and from Idyllshire now work, as well as the Aethernet in Idyllshire
> Added all Zonelines for Idyllshire

- sql/zonepositions.sql
Added all the zonelines for the Aethernet in all of Foundation and The Pillars
> Added Foundation/The Pillars Aethernet

- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/Server_Zone/Network/Handlers/GMCommandHandlers.cpp
-Added the //gm teri <ZoneID> command (Can also use internal name)
-Removed the Debug Commands that has GM Counter parts (ex. @set zone <ZoneID>) in effort to clean them up
> //gm teri and Debug Cleanup

- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/Server_Zone/Network/Handlers/GMCommandHandlers.cpp
The @set eorzeatime Command is now //gm time <Value>
> Made the @set eorzeatime A GM Command

- sql/zonepositions.sql
Added the zonepositions for the Rhalgr's Reach Aethernet
> Added Rhalgr's Reach Aethernet

- src/servers/Server_Zone/Network/Handlers/PacketHandlers.cpp
See #109 comments
Didn't bother to test; obviously "testing in production" is the best method! /s
> Change command prefix to !

- src/servers/Server_Common/Common.h
-Added Some Territory Intended Use Types to Common.h
TODO: 
- Add The Rest of The Territory Types since a lot are missing and I could not work out what they where
- Have Better Names For the TerritoryIntendedUseTypes
> Added Some TerritoryIntendedUseTypes to Common

- scripts/chai/opening/OpeningGridania.chai
- scripts/chai/opening/OpeningLimsa.chai
- scripts/chai/opening/OpeningUldah.chai
- scripts/chai/quest/ManFst003.chai
- scripts/chai/quest/ManSea001.chai
- scripts/chai/quest/ManWil001.chai
- Fixed the Coming to Ul'dah and Coming to Limsa Quest
- Fixed the Openings having Black Bars and not being able to jump until another scene played
- Fixed Close To Home (Archer) so now the sequence moves on to the next task
The Coming to Quests might have to be looked at a little more to make sure they are fine with the event params. Other then that people can Accept and Do the Quests now
> Added All Coming To X Quests, Fixed Opening Black Bars and Close to Home (Archer)

- bin/web/createUser.html
- bin/web/login.html
Who did they hire to write this pile of crap called internet explorer
> No Scroll Bars for Login/Create User

- sql/charadetail.sql
- sql/update.sql
- src/servers/Server_Common/Common.h
- src/servers/Server_Common/Network/PacketDef/Ipcs.h
- src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/Server_Zone/Actor/Actor.h
- src/servers/Server_Zone/Actor/Player.cpp
- src/servers/Server_Zone/Actor/Player.h
- src/servers/Server_Zone/Actor/PlayerSql.cpp
- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/Server_Zone/Network/GameConnection.cpp
- src/servers/Server_Zone/Network/GameConnection.h
- src/servers/Server_Zone/Network/Handlers/PacketHandlers.cpp
- src/servers/Server_Zone/Network/PacketWrappers/PlayerSpawnPacket.h
- src/servers/Server_Zone/Session.cpp
~~TODO: find field in PlayerSpawn~~
Update: The field has been found.
> Gear params

- scripts/chai/CmnDef/CmnDefCutSceneReplay.chai
- scripts/chai/CmnDef/CmnDefInnBed.chai
- scripts/chai/CmnDef/HouFurOrchestrion.chai
TODO: 
* Figure out why bed isn't shown in the wake up cutscene and "This cutscene cannot be skipped" doesn't appear
* Make Orchestrion script check if in private housing area and show the playlist menu
> CmnDefInnBed, CmnDefCutSceneReplay, HouFurOrchestrion

- src/servers/Server_Zone/Actor/PlayerSql.cpp
- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
Was gonna use my PR for these but that's gone now
Align the codebase with what @takhlaq requested
> Align codebase with req changes;

- src/servers/Server_Common/Network/PacketDef/Chat/ServerChatDef.h
- src/servers/Server_Common/Network/PacketDef/Ipcs.h
- src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
- src/servers/Server_Zone/Network/PacketWrappers/PlayerSpawnPacket.h
Just GMRank, playerstats, chat tell, title etc;
> Updating stuff for 4.1;

- src/servers/Server_Common/Exd/ExdData.cpp
- src/servers/Server_Common/Exd/ExdData.h
- src/servers/Server_Common/Network/PacketDef/Ipcs.h
Effect IPC was updated to conform 4.1 changes.
New definitions for status effects.
More to come, as ideally we should have them all mapped for status effect implementation (and thus knowing exactly what we need to set up in their scripts)
> Effect IPC updated; Definitions for status effect exd;

- scripts/chai/CmnDef/CmnDefInnBed.chai
Fixed the bed not showing up when waking up in a Inn
> Fixed Bed Not Showing Up When Waking Up

- .gitignore
- vcxproj/sln files created using cmake tool
- idb files made as a result of build
> Remove CMake/Build Artifacts

- src/servers/Server_Common/Common.h
- src/servers/Server_Common/Network/GamePacket.cpp
- src/servers/Server_Common/Network/PacketDef/Ipcs.h
- src/servers/Server_Common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/Server_Common/Util/Util.cpp
- src/servers/Server_Common/Util/Util.h
- src/servers/Server_Zone/Action/ActionMount.cpp
- src/servers/Server_Zone/Action/ActionMount.h
- src/servers/Server_Zone/Actor/Player.cpp
- src/servers/Server_Zone/Actor/Player.h
- src/servers/Server_Zone/Actor/PlayerSql.cpp
- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/Server_Zone/Forwards.h
- src/servers/Server_Zone/Network/GameConnection.cpp
- src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
- src/servers/Server_Zone/Network/Handlers/SkillHandler.cpp
- src/servers/Server_Zone/Network/PacketWrappers/InitUIPacket.h
- src/servers/Server_Zone/Network/PacketWrappers/PlayerSpawnPacket.h
TODO: Figure out the mount guide bitmask size/position in InitUI
> Initial mounts implementation, nicer debug packet printing

- src/tools/pcb_reader/main.cpp
- src/tools/pcb_reader/sgb.h
- fixed loading some gimmick entries
> cleaned up some compiler warnings in pcb_reader

- src/servers/Server_Common/Crypt/base64.cpp
- src/servers/Server_Lobby/client_http.hpp
- src/servers/Server_REST/main.cpp
- src/servers/Server_REST/server_http.hpp
- src/servers/Server_Zone/Actor/BattleNpc.cpp
- src/servers/Server_Zone/Actor/CalcBattle.cpp
- src/servers/Server_Zone/Actor/Player.cpp
- src/servers/Server_Zone/Actor/PlayerQuest.cpp
- src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
- static_cast for reasonable values
- at least one stray float
> Fixing some type alignments via casting

- .gitignore
- src/servers/Server_Common/Exd/ExdData.cpp
- src/servers/Server_Zone/Actor/Actor.cpp
- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/Server_Zone/DebugCommand/DebugCommandHandler.h
- src/servers/Server_Zone/Network/Handlers/ActionHandler.cpp
- src/servers/Server_Zone/Network/Handlers/GMCommandHandlers.cpp
- src/servers/Server_Zone/Script/ScriptManager.cpp
- src/servers/Server_Zone/Script/ScriptManagerInit.cpp
- fix //gm teri allowing invalid locations and preventing login
- ignore files generated by edit and continue
- improve debug output for quest interactions
- !unlock command to call player.unlock()
- !help lists all debug commands you have access to
- fix teleporting
> misc bugfixes and improvements

- src/servers/Server_REST/main.cpp
- src/servers/Server_REST/server_http.hpp
- exceptions had unused parameters
> Remove unreferenced parameters

- cmake/compiler.cmake
- src/servers/Server_Lobby/CMakeLists.txt
- src/servers/Server_REST/CMakeLists.txt
- src/servers/Server_Zone/CMakeLists.txt
- remove /SAFESEH:NO
- apply /INCREMENTAL /ZI (debug only)
- remove sprinkling of /INCREMENTAL /ZI
> Fix up Flags around Edit and Continue

- src/servers/Server_Zone/Actor/Player.h
- src/servers/Server_Zone/Actor/PlayerInventory.cpp
- move tryAddItem/AddItem to uint32_t from uint16_t
> Quantity treated as uint32_t at packet level

- sql/infolinkshell.sql
- src/servers/Server_Zone/Actor/PlayerQuest.cpp
- src/servers/Server_Zone/Inventory/Inventory.cpp
- src/servers/Server_Zone/Linkshell/LinkshellMgr.cpp
- src/servers/Server_Zone/Linkshell/LinkshellMgr.h
- src/servers/Server_Zone/Network/Handlers/EventHandlers.cpp
- expand some types
- gnarly std::pair issue with short to int8_t
- getLinkshellById now uses uint32_t
> More static_cast

- src/servers/Server_REST/main.cpp
- don't be too smart without running through some testing
> Path comparison is causing issues

- src/servers/Server_REST/PlayerMinimal.cpp
- src/servers/Server_REST/SapphireAPI.cpp
Fix small stuff. On char creation there's still an issue involving getting uniqueId in saveAsNew(), haven't been able to look into it too much.
> Small acc creation fixes;

- bin/config/settings_zone.xml
- src/servers/Server_Zone/Script/ScriptManager.cpp
- src/servers/Server_Zone/Script/ScriptManagerInit.cpp
- src/servers/Server_Zone/ServerZone.cpp
Add a configuration option and default to the Chai script loader.
> Fix #183 hardcoded Chai scripts path

- sql/import.bat
Fixed import.bat to include password on import loop and update.sql imort
> Fixed import.bat to include password on import loop and update.sql imort

- src/tools/pcb_reader/README.md
- src/tools/pcb_reader/main.cpp
- note that expansions still wont load as xivdat needs some work
> updated pcb_reader to read territorytype from ffxivexplorer export

- src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.h
- src/servers/sapphire_zone/Network/GameConnection.cpp
- src/servers/sapphire_zone/Session.cpp
- src/servers/sapphire_zone/Session.h
This may need millisecond accuracy for sets in the future, since currently they are only processed per full second
> Added basic capture replay

- src/servers/sapphire_zone/Network/Handlers/GMCommandHandlers.cpp
GM Call was placed in GM1 instead of GM2 for some reason /shrug
> Fixed GM Call

- CMakeLists.txt
- src/tools/pcb_reader/CMakeLists.txt
- src/tools/pcb_reader/main.cpp
> reenable pcb_reader build

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.cpp
```!set msqguide 57```
```!set msqdone 57```
> Add MSQ guide def

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
Fixed OnlineStatus removing itself for players on spawn
Fixed Some SearchInfo Ipc's
> Updated SearchInfo IPC's and Fixed OnlineStatus

- src/common/Network/PacketDef/Ipcs.h
- src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/sapphire_zone/ServerZone.cpp
> opcode update, cleanup and maybe disconnect issue fixed?

- src/tools/pcb_reader/lgb.h
- src/tools/pcb_reader/main.cpp
- src/tools/pcb_reader/sgb.h
- todo: why the fuck did eobj/maprange dump break?
> added option to dump instance level.exd entries to pcb_reader

- src/common/Network/PacketDef/Ipcs.h
- src/tools/pcb_reader/main.cpp
> fix windows paths with pcb reader

- src/servers/sapphire_zone/Actor/GameObject.cpp
- src/servers/sapphire_zone/Actor/GameObject.h
- src/servers/sapphire_zone/Actor/InstanceObject.cpp
- src/servers/sapphire_zone/Actor/InstanceObject.h
- src/servers/sapphire_zone/Forwards.h
- src/servers/sapphire_zone/Script/NativeScriptApi.h
- src/servers/sapphire_zone/Script/ScriptManager.cpp
- src/servers/sapphire_zone/Script/ScriptManager.h
- src/servers/sapphire_zone/Script/Scripts/CMakeLists.txt
- src/servers/sapphire_zone/Script/Scripts/ScriptLoader.cpp.in
- src/servers/sapphire_zone/Script/Scripts/instances/trials/TheNavel.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.h
packet stuff still needs to be done and it probably will work:tm:
> instance scripting + object creation

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/sapphire_zone/Actor/Player.cpp
- src/servers/sapphire_zone/Actor/Player.h
- src/servers/sapphire_zone/Actor/PlayerEvent.cpp
- src/servers/sapphire_zone/Network/Handlers/EventHandlers.cpp
- src/servers/sapphire_zone/Network/PacketWrappers/EventStartPacket.h
- src/servers/sapphire_zone/Script/ScriptManager.cpp
- src/servers/sapphire_zone/Script/ScriptManager.h
- src/servers/sapphire_zone/Zone/InstanceContent.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.h
- src/servers/sapphire_zone/Zone/Zone.cpp
- src/servers/sapphire_zone/Zone/Zone.h
> fix onEnterTerritory events, eventstart handling for instances

- src/common/Util/SpawnIndexAllocator.h
reduce a few warnings to make debugging this thing a little easier
> const correct

- src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.h
`!instance qte_start`
`!instance event_start`
`!instance event_end`
Must be on the map that supports it.
Code quality is not guaranteed™
> Add a qte event command

- src/common/Common.h
- src/common/Network/PacketDef/Ipcs.h
- src/servers/sapphire_zone/Actor/Player.h
- src/servers/sapphire_zone/Actor/PlayerEvent.cpp
- src/servers/sapphire_zone/DebugCommand/DebugCommandHandler.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.cpp
- src/servers/sapphire_zone/Zone/InstanceContent.h
now with 200% more masayoshi soken 👌 🔥 💯
> instance bgm works now

- src/servers/sapphire_zone/Zone/InstanceContent.cpp
> Implement director wide bgm

- src/servers/Scripts/quest/ManSea001.cpp
Quest Script: ManSea001_00107
Quest Name: Coming to Limsa Lominsa
Old script:
- Events locked at Scene00003 (no QuestUpdate)
Actually:
- QuestUpdate set on Scene00003
- Add "If param2" on Scene00006 (because Actor1 ask if we want change position)
PS: I modified the entire script for a better understanding (imho)
> ManSea001 now work properly

- src/servers/Scripts/quest/ManSea002.cpp
- src/servers/Scripts/quest/ManSea003.cpp
- src/servers/Scripts/quest/subquest/limsa/SubSea001.cpp
Before:
- No start cutscene
- Wrong settings
Now:
- Start cutscene
- All quest credits work
- MSQ can be complete
NOTE: For a properly zoning, player need to accept Mansea002 and Subsea001.
> ManSea002 now work properly

- src/servers/Scripts/action/ActionReturn6.cpp
Just Return (action 6) now teleport correctly player to the favourite Aetheryte
> Return (Action 6) now work (again?)

- src/servers/sapphire_zone/Actor/Player.cpp
- src/servers/sapphire_zone/Actor/Player.h
- src/servers/sapphire_zone/Network/Handlers/GMCommandHandlers.cpp
- src/servers/sapphire_zone/Network/Handlers/PacketHandlers.cpp
- src/servers/sapphire_zone/Zone/TerritoryMgr.cpp
- src/servers/sapphire_zone/Zone/TerritoryMgr.h
- Fixed making new zones, and also made it look the way it does on createDefaultTerritories
- Added GuId to //gm teri_info and also fixed the spacing
- GM Raise is now using the new zoneinpacket system so it does not leak packets if invis
- GM Chat is now done via OnlineStatus since Adam complained about it being all the time :p
> Fixed making new zones and done some more gm stuff

- src/servers/Scripts/common/CmnDefMogLetter.cpp
Initial script for Mail npcs
#180
> Cmndefmogletter script added

- bin/web/assets/css/global.css
- bin/web/assets/css/styles.css
- bin/web/createUser.html
- bin/web/login.html
- src/common/Network/CommonActorControl.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/sapphire_lobby/GameConnection.cpp
- src/servers/sapphire_zone/Actor/Player.cpp
- src/servers/sapphire_zone/Actor/Player.h
- src/servers/sapphire_zone/Network/Handlers/ClientTriggerHandler.cpp
- src/servers/sapphire_zone/Network/PacketWrappers/PlayerSpawnPacket.h
- src/tools/exd_struct_gen/ex.json
More emote stuff + bit of launcher;
> Emote stuff;

- src/servers/Scripts/common/CmnDefMogLetter.cpp
- src/servers/Scripts/quest/ManFst003.cpp
- src/servers/Scripts/quest/ManFst004.cpp
- Manfst004 currently work properly
- Little typo on ManFst003
- Mog now talks to players
> Manfst004 now work + Mog happy

- src/servers/Scripts/quest/subquest/limsa/SubSea001.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil000.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil001.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil002.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil004.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil006.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil007.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil018.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil019.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil021.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil022.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil027.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil028.cpp
- src/servers/Scripts/quest/subquest/uldah/SubWil029.cpp
Done:
This will be ready to merge at least with 15 scripts
> Ul'dah sidequests added + style

- src/common/Network/CommonActorControl.h
- src/servers/sapphire_zone/Network/Handlers/GMCommandHandlers.cpp
- Added Wireframe Rendering Actorcontrol type
- Added GM Wireframe Command to toggle it
> Added Wireframe Rendering Actorcontrol type and GM Wireframe command

- src/common/Network/CommonActorControl.h
- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/servers/sapphire_zone/Network/GameConnection.cpp
- src/servers/sapphire_zone/Network/GameConnection.h
- src/servers/sapphire_zone/Network/Handlers/ClientTriggerHandler.cpp
- src/servers/sapphire_zone/Network/Handlers/PacketHandlers.cpp
- src/servers/sapphire_zone/Network/PacketWrappers/ExaminePacket.h
- src/servers/sapphire_zone/Network/PacketWrappers/PlayerSpawnPacket.h
- todo: fix gear models not displaying
> added basic examine functionality

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- Added MailDeleteRequest opcode
- Added ReqMoogleMailList opcode and packetDef
- Added ReqMoogleMailLetter opcode
- Added MailLetterNotification opcode and packetDef
These still have some unknowns in them for now, Ill need to play around more with these but it should do for now
Tagging #180 in this PR to keep track of whats been done and needs to be done
> Add some Moogle Mail PacketDefs and Opcodes

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ClientZoneDef.h
- src/servers/sapphire_zone/Network/Handlers/GMCommandHandlers.cpp
- Fixed /playtime by updating the server opcode
- Fully mapped out GMCommand 1 & 2 expect one unknown
- Adjusted the GmCommandHandler to accept the new params
> GMCommand1 & 2 almost fully mapped / Fixed /playtime

- src/servers/sapphire_api/PlayerMinimal.cpp
- src/servers/sapphire_zone/Actor/Player.h
- src/servers/sapphire_zone/Actor/PlayerInventory.cpp
Before merging, please keep in mind that this will crash the zone server if you try to login with a corrupt character (specifically one that is holding a weapon of a different class).
Referencing #308 for progress.
> Add class change on weapon swaps. Also adds a forgotten inventory on character creation.

- src/servers/sapphire_zone/Actor/PlayerInventory.cpp
> Thanks Adam. Change c-style cast.

- bin/web/login.html
Just press Enter after insert your password and it will open client without click on Login button
> [Launcher] Press Enter after password and finally instant open client

- src/scripts/quest/subquest/gridania/SubFst005.cpp
- src/scripts/quest/subquest/gridania/SubFst045.cpp
To the Bannock and Passing Muster now work properly (And this time they can be merged)
> [Quest] SubFst005 + SubFst045

- src/tools/discovery_parser/lgb.h
- src/tools/discovery_parser/main.cpp
- src/tools/pcb_reader/lgb.h
- src/tools/pcb_reader/main.cpp
- src/tools/pcb_reader/sgb.h
- requires RecastDemo built from https://github.com/takhlaq/recastnavigation/tree/garbage
- copy recastdemo.exe, sdl.dll, sdl2.dll into same directory as pcb_reader exe
> navmesh generation in pcb_reader

- src/tools/pcb_reader/cache.h
- src/tools/pcb_reader/navmesh_exporter.h
- src/tools/pcb_reader/threadpool.h
- purge cache every 1000 files
- fixed issues with threadpool
- attempt at using recast api to generate navmesh (doesnt work)
> pcb_reader:

- src/world/Actor/BNpc.cpp
- src/world/Actor/BNpc.h
- src/world/CMakeLists.txt
- src/world/Manager/DebugCommandMgr.cpp
- src/world/Manager/NaviMgr.cpp
- src/world/Manager/NaviMgr.h
- src/world/Manager/TerritoryMgr.cpp
- src/world/Navi/NaviProvider.cpp
- src/world/Navi/NaviProvider.h
- src/world/ServerMgr.cpp
- src/world/Territory/Zone.cpp
- src/world/Territory/Zone.h
* Adds a new NaviMgr Manager class that loads NaviProviders which provide pathfinding services to NPCs in Zones
* Adds basic path tracking code to BNpc
> Basic pathfinding

- src/common/Network/PacketDef/Ipcs.h
✅ :shit: 👌 
✅ room temperature IQ
> 🀄 opcodes 

- src/common/Config/ConfigDef.h
- src/world/Manager/TerritoryMgr.cpp
- src/world/Navi/NaviProvider.cpp
- src/world/ServerMgr.cpp
- src/world/Territory/Zone.cpp
> fix things

- src/scripts/quest/ManWil003.cpp
- src/scripts/quest/ManWil004.cpp
Pugilist and THM "Close to Home" Main Story Quests.
As requested by NotAdam, PR'ing this into Dev.
> Pugilist and THM Close to Home MSQ scripts

- sql/schema/schema.sql
- src/common/Exd/ExdDataGenerated.cpp
- src/common/Exd/ExdDataGenerated.h
- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/common/Util/Util.cpp
- src/common/Util/Util.h
- src/dbm/DbManager.cpp
- src/dbm/DbManager.h
- src/dbm/main.cpp
- src/tools/exd_struct_gen/ExdData.cpp.tmpl
- src/tools/exd_struct_gen/ExdData.h.tmpl
- src/tools/exd_struct_gen/main.cpp
- src/world/Action/Action.cpp
- src/world/Actor/Chara.cpp
- src/world/Actor/Player.cpp
- src/world/Actor/PlayerEvent.cpp
- src/world/Actor/PlayerSql.cpp
- src/world/Manager/DebugCommandMgr.cpp
- src/world/Network/GameConnection.cpp
- src/world/Network/Handlers/ClientTriggerHandler.cpp
- src/world/Network/Handlers/GMCommandHandlers.cpp
- src/world/Network/Handlers/PacketHandlers.cpp
- src/world/Network/PacketWrappers/PlayerSetupPacket.h
also 2 space formatting instead of 3 👏
> update exd_struct_gen to new saintcoinach defs structure

- src/common/Network/CommonActorControl.h
I'm not sure the new name (`DesynthOrReduceResult`) is a good one so feel free to rename it before merge or just tell me if there's a better name for this 😄
> Update DesynthResult actorControl

- src/common/Exd/ExdDataGenerated.cpp
- src/common/Exd/ExdDataGenerated.h
- src/common/Network/PacketDef/Ipcs.h
> 5.1 opcode updates

- src/world/Action/Action.cpp
- src/world/Actor/BNpc.cpp
- src/world/Actor/Chara.cpp
- src/world/Manager/DebugCommandMgr.cpp
- src/world/Manager/HousingMgr.cpp
- src/world/Math/CalcStats.cpp
- src/world/Network/GameConnection.cpp
- src/world/Network/Handlers/CFHandlers.cpp
- src/world/Network/Handlers/ClientTriggerHandler.cpp
- src/world/Network/Handlers/GMCommandHandlers.cpp
- src/world/Territory/Cell.cpp
- src/world/Territory/House.cpp
- src/world/Territory/Housing/HousingInteriorTerritory.cpp
using static and reinterpret casts instead of old style casts
comparing floating point with "==" or "!=" is not correct (Chara.cpp)
> fix warnings

- src/common/Network/PacketDef/Ipcs.h
- src/world/Actor/PlayerInventory.cpp
Update inventory opcodes. (now discard item works)
Play the sound effect when getting new items.
> Inventory fixes.

- src/common/Common.h
- src/scripts/action/common/ActionSprint3.cpp
- src/world/Action/Action.cpp
- src/world/Action/Action.h
- src/world/Action/EffectBuilder.cpp
- src/world/Action/EffectBuilder.h
- src/world/Action/EffectResult.cpp
- src/world/Action/EffectResult.h
and add the "+sprint" flying text effect when using sprint.
> Allow action scripts to add effect.

- src/scripts/common/GilShop.cpp
- src/world/Actor/Player.h
- src/world/Actor/PlayerEvent.cpp
When selling the sound effect is also played (and shop switch to buy back tab as well) but the selling logic code is not there so...
> Play the coin sound effect when buying items from shop.

- src/common/Common.h
- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/world/Action/Action.cpp
- src/world/Actor/BNpc.cpp
- src/world/Actor/Chara.cpp
- src/world/Actor/Chara.h
- src/world/Actor/Player.cpp
- src/world/Actor/PlayerEvent.cpp
- src/world/Network/PacketWrappers/NpcSpawnPacket.h
- src/world/Network/PacketWrappers/PlayerSpawnPacket.h
Stuff picked up from closed PR.
> enum/struct/packet updates, fix dot/hot tick, remove incorrect initial delay for player autoattacks.

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/world/Actor/Chara.cpp
- src/world/Actor/Player.cpp
- src/world/Network/PacketWrappers/NpcSpawnPacket.h
- src/world/Network/PacketWrappers/PlayerSpawnPacket.h
should be able to login and do basic stuff
> 5.2 packet update.

- src/common/Network/PacketDef/Ipcs.h
- src/world/Actor/Player.cpp
When the map is fully completed, gain an additional EXP bonus equal to 10 times the regular amount.
> Additional EXP bonus on full map completion

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/world/Manager/DebugCommandMgr.cpp
Used to show effects like war beast gauge and drk darkside.
If a better name already exists please comment and I'll update it.
> Add CharaVisualEffect packet.

- src/common/Network/CommonActorControl.h
- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/scripts/action/common/ActionDye2472.cpp
- src/world/Actor/Player.cpp
- src/world/Actor/Player.h
- src/world/Network/Handlers/ClientTriggerHandler.cpp
- src/world/Network/PacketWrappers/ExaminePacket.h
- src/world/Network/PacketWrappers/UpdateInventorySlotPacket.h
Functional, but doesn't remove any dyes on use, and doesn't line up 1:1 with retail packets I'm sure.
As a bonus, fixed up some of the Examine stuff so dyes show up properly when you examine a player.
> implemented dyeable items

- src/common/Common.h
- src/world/Actor/Player.cpp
- src/world/Actor/Player.h
- src/world/Manager/DebugCommandMgr.cpp
- src/world/Network/Handlers/PacketHandlers.cpp
Also show job ui on client, debug command to manipulate raw bytes
> JobGauge definition.

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/scripts/common/GilShop.cpp
- src/world/Actor/Player.cpp
- src/world/Actor/Player.h
- src/world/Actor/PlayerEvent.cpp
- src/world/Actor/PlayerInventory.cpp
- src/world/Event/EventHandler.h
- src/world/Manager/ShopMgr.cpp
- src/world/Manager/ShopMgr.h
- src/world/Network/Handlers/EventHandlers.cpp
- src/world/Network/PacketWrappers/UpdateInventorySlotPacket.h
- src/world/Script/ScriptMgr.cpp
Also fix build error from last PR.
>  Selling items and buying back from shop, show corresponding messages in chat.

- src/common/Common.h
- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
Add the IPC + opcode, add its structure too. Baby's first PR.
> Add PlaceFieldMarkerPreset IPC

- src/scripts/quest/classquest/ARC/ClsArc000.cpp
- src/scripts/quest/classquest/ARC/ClsArc001.cpp
- src/scripts/quest/classquest/ARC/ClsArc002.cpp
- src/scripts/quest/classquest/ARC/ClsArc003.cpp
- src/scripts/quest/classquest/ARC/ClsArc004.cpp
- src/scripts/quest/classquest/ARC/ClsArc005.cpp
- src/scripts/quest/classquest/ARC/ClsArc006.cpp
Hi everyone!
Finally I'm back to fix! 😃 
With this pull request Arc chain quest will be complete.
Just a couple of things to fix ( need someone better than me for this ):
- Questbattles are broken: I can't init them that world.exe crash (Log trace below)
[questbattles.txt](https://github.com/SapphireServer/Sapphire/files/4807183/questbattles.txt)
Last try at commit 7ac677c70f8f6b6b8cdd7b3ee79dab43a32e4a94
- EventActionStart on Eobj doesn't work properly: player's animation start correctly but world.exe crash...
I found a temporary solution with "EventStart": it lets going well with the quest but appear a "Event Cancelled" red warning everytime that call function.
- Need an external text with ClsArc005: do ingame //gm quest seq 65606 4 and talk to eobj for complete the task, go and try to …
> Class Quests ARC

- src/common/Network/PacketDef/Ipcs.h
- src/world/Network/GameConnection.cpp
Seen in quests where the player trade more than 1 stack of items to an npc.
> Add TradeMultipleReturnEventHander

- src/common/Network/PacketDef/Ipcs.h
Anyways, this one isn't supposed to be here.
> Remove UseMooch since the detection for this is actually InventoryTransaction and the packet is SomeDirectorUnk4 or something

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
> MiniCactpotInit opcode and documentation; MarketTaxRates tweak

- src/common/Network/PacketDef/Ipcs.h
All of the known IPCs from opcodes channel for 5.35 now that 5.35 hotfix is out.
> update IPCs for 5.35

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ClientZoneDef.h
- src/world/Inventory/ItemContainer.cpp
- src/world/Manager/HousingMgr.cpp
- src/world/Manager/HousingMgr.h
- src/world/Manager/InventoryMgr.cpp
- src/world/Manager/TerritoryMgr.cpp
- src/world/Network/GameConnection.cpp
- src/world/Network/GameConnection.h
- src/world/Network/Handlers/PacketHandlers.cpp
- src/world/Territory/House.cpp
- src/world/Territory/House.h
- src/world/Territory/Land.cpp
- src/world/Territory/Land.h
With EventYield opcode thrown into it.
> Housing bug fixes and implement house exterior editing.

- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ClientZoneDef.h
- src/world/Manager/HousingMgr.cpp
- src/world/Manager/HousingMgr.h
- src/world/Network/GameConnection.cpp
- src/world/Network/GameConnection.h
- src/world/Network/Handlers/PacketHandlers.cpp
And some opcode updates thrown in as well.
> Implement housing edit interior.

- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/world/Network/PacketWrappers/PlayerSetupPacket.h
> fix world expansion level;

- src/scripts/quest/classquest/ARC/ClsArc000.cpp
- src/scripts/quest/classquest/ARC/ClsArc001.cpp
- src/scripts/quest/classquest/ARC/ClsArc002.cpp
- src/scripts/quest/classquest/ARC/ClsArc003.cpp
- src/scripts/quest/classquest/ARC/ClsArc004.cpp
- src/scripts/quest/classquest/ARC/ClsArc005.cpp
- src/scripts/quest/classquest/ARC/ClsArc006.cpp
- src/scripts/quest/classquest/ARC/ClsArc100.cpp
- src/scripts/quest/classquest/ARC/ClsArc997.cpp
- src/scripts/quest/classquest/ARC/ClsArc998.cpp
- src/scripts/quest/classquest/ARC/ClsArc999.cpp
Some are backports, some are original. 
QuestBattle stuff is currently broken so I've had to comment out and skip over the fights. A debug message will show up telling players about this,
> [3.0] Implement ARC questline

- src/scripts/quest/classquest/ARC/ClsArc001.cpp
- src/scripts/quest/classquest/ARC/ClsArc002.cpp
- src/scripts/quest/classquest/ARC/ClsArc003.cpp
- src/scripts/quest/classquest/ARC/ClsArc004.cpp
- src/scripts/quest/classquest/ARC/ClsArc005.cpp
- src/scripts/quest/classquest/ARC/ClsArc006.cpp
- src/scripts/quest/classquest/ARC/ClsArc100.cpp
- src/scripts/quest/classquest/ARC/ClsArc997.cpp
Oh hey I have to make the sequence completion text show up myself.
> [3.0] More ARC cleanup

- src/scripts/quest/classquest/CNJ/ClsCnj000.cpp
- src/scripts/quest/classquest/CNJ/ClsCnj001.cpp
- src/scripts/quest/classquest/CNJ/ClsCnj002.cpp
- src/scripts/quest/classquest/CNJ/ClsCnj003.cpp
- src/scripts/quest/classquest/CNJ/ClsCnj004.cpp
- src/scripts/quest/classquest/CNJ/ClsCnj005.cpp
- src/scripts/quest/classquest/CNJ/ClsCnj006.cpp
Entire questline for one who starts as a CNJ. Will need to implement 100/997/998/999 for players who start as something else.
> [3.0] CNJ Quests

- src/scripts/quest/classquest/ARC/ClsArc000.cpp
- src/scripts/quest/classquest/ARC/ClsArc001.cpp
- src/scripts/quest/classquest/ARC/ClsArc002.cpp
- src/scripts/quest/classquest/ARC/ClsArc003.cpp
- src/scripts/quest/classquest/ARC/ClsArc004.cpp
- src/scripts/quest/classquest/ARC/ClsArc005.cpp
- src/scripts/quest/classquest/ARC/ClsArc006.cpp
- src/scripts/quest/classquest/ARC/ClsArc100.cpp
- src/scripts/quest/classquest/ARC/ClsArc997.cpp
- src/scripts/quest/classquest/ARC/ClsArc998.cpp
- src/scripts/quest/classquest/ARC/ClsArc999.cpp
Ran the new clang on the ARC scripts and also replaced a couple of outdated player calls with quest calls.
> ARC clang cleanup

- src/api/PlayerMinimal.cpp
- src/api/SapphireApi.cpp
- src/lobby/LobbyPacketContainer.cpp
- src/lobby/LobbyPacketContainer.h
- src/lobby/RestConnector.cpp
- src/tools/quest_parser/main.cpp
- src/world/Action/Action.cpp
- src/world/Action/Action.h
- src/world/Action/ItemAction.cpp
- src/world/Actor/BNpc.cpp
- src/world/Actor/BNpc.h
- src/world/Actor/Player.cpp
- src/world/Actor/Player.h
- src/world/Manager/HousingMgr.cpp
- src/world/Manager/InventoryMgr.cpp
- src/world/Manager/PlayerMgr.cpp
- src/world/Network/Handlers/PacketCommandHandler.cpp
- src/world/Territory/HousingZone.cpp
- src/world/Territory/Territory.cpp
- src/world/Territory/Territory.h
i'm not confident still on pulling bnpc out of territory because of the lookups
it'd be possible to use nearby player actors, but that opens a can of its own
> bnpc/hatelist aggro value+rate work; action aggroMultiplier; warning cleanups;

- src/scripts/quest/subquest/gridania/SubFst002.cpp
- src/scripts/quest/subquest/gridania/SubFst007.cpp
- src/scripts/quest/subquest/gridania/SubFst011.cpp
- src/scripts/quest/subquest/gridania/SubFst021.cpp
- src/scripts/quest/subquest/gridania/SubFst025.cpp
- src/scripts/quest/subquest/gridania/SubFst026.cpp
- src/scripts/quest/subquest/gridania/SubFst037.cpp
- src/scripts/quest/subquest/gridania/SubFst039.cpp
- src/scripts/quest/subquest/gridania/SubFst041.cpp
- src/scripts/quest/subquest/gridania/SubFst042.cpp
- src/scripts/quest/subquest/limsa/SubSea012.cpp
Should be the last of the subquest backports from master.
> [3.0] Subquest backports

- src/scripts/quest/ManSea001.cpp
Script comes from the_movie parser with one line added, I assume having a different code structure than the c++ template is okay?
> fix limsa first quest

- src/world/ContentFinder/ContentFinder.cpp
- src/world/ContentFinder/ContentFinder.h
- src/world/Network/Handlers/CFHandlers.cpp
- src/world/Network/PacketWrappers/UpdateContentPacket.h
Undersized still needs some work as the numbers don't display properly and each QueuedContent needs to be separate for undersized queues (otherwise you can get put in the same instance).
> [3.x] CF commence and undersized implemented

- .github/workflows/build.yml
Switch to windows-2019 instead of windows-latest
> [3.0] Update github workflow build.yml

- src/scripts/quest/festivalquest/FesEst101.cpp
- src/scripts/quest/festivalquest/FesEst102.cpp
- src/scripts/quest/festivalquest/FesEst103.cpp
Was sitting on my local dev environment. No idea why it wasn't pushed in the past.
> [3.0] Hatching-tide 2015

- src/tools/nav_export/exportmgr.h
- src/tools/nav_export/main.cpp
- src/tools/nav_export/pcb.h
- src/tools/nav_export/threadpool.h
- re-add multithreaded exporting and make it eat less ram
> [3.x] fix nav_export for 3.05

- src/scripts/quest/classquest/WHM/JobWhm001.cpp
- src/scripts/quest/subquest/thanalan_west/SubWil142.cpp
Left a fake func behind for all dungeon completion related steps.
> [3.0] WHM ARR Relic Quest (w/ Psuedocode)

- src/scripts/quest/subquest/gridania/BanIxa001.cpp
- src/scripts/quest/subquest/gridania/BanSyl001.cpp
- src/scripts/quest/subquest/gridania/GaiUsa907.cpp
- src/scripts/quest/subquest/gridania/GaiUsa908.cpp
- src/scripts/quest/subquest/gridania/SubFst012.cpp
- src/scripts/quest/subquest/gridania/SubFst159.cpp
Should be everything except Dungeon unlocks and Sightseeing Log unlock quest.
> [3.0] Gridania Sidequests

- src/scripts/quest/ManWil004.cpp
Fixed in a similar way to the changes done for ManFst002
> Fixing the starting Ul'dah quest (ManWil004) by using the new bindSceneReturn API 

- .gitignore
- src/common/Common.h
- src/common/Database/DbConnection.cpp
- src/common/Network/CommonActorControl.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/world/Actor/Player.cpp
- src/world/Actor/Player.h
- src/world/Manager/AchievementMgr.cpp
- src/world/Manager/AchievementMgr.h
- src/world/Manager/DebugCommandMgr.cpp
- src/world/Manager/PlayerMgr.cpp
- src/world/Manager/PlayerMgr.h
- src/world/Network/Handlers/GMCommandHandlers.cpp
- src/world/Network/Handlers/PacketCommandHandler.cpp
- src/world/WorldServer.cpp
so far only tested with achievement type: general (1),  linkedachievements (2) and classjob (3)
no SQL yet due to possible data issues still and type handlers not being fully mapped out
> [3.x] achievement implementation; partial achievementsubtype mapping; styling fixes;

- src/tools/quest_parser/main.cpp
- add actor and item names as comments
- add actor positions as comments (bnpc/eobj teris may be inaccurate)
- sort script entities properly with shameless natural sort steal
> quest parser improvements

- src/world/Manager/AchievementMgr.h
- src/world/Manager/PlayerMgr.cpp
> [3.x] better comments on achievement usage; get level from player object for classjob achievements;

- src/common/Database/ZoneDbConnection.cpp
- src/world/Inventory/ItemContainer.cpp
- src/world/Manager/HousingMgr.cpp
- src/world/Manager/HousingMgr.h
- src/world/Manager/InventoryMgr.cpp
- src/world/Network/Handlers/ClientTriggerHandler.cpp
- src/world/Territory/HousingZone.cpp
- src/world/Territory/HousingZone.h
Well, if anyone is still using this branch.
> Handle house removing.

- deps/mysqlConnector/Connection.cpp
- src/common/Database/ZoneDbConnection.cpp
> db: remove extraneous comma from fc prepared statement

- src/scripts/CMakeLists.txt
- src/world/Script/NativeScriptMgr.cpp
- src/world/Script/NativeScriptMgr.h
- src/world/Script/ScriptLoader.cpp
> scripts: build modules to tmp directory before copying over to reload

- src/common/Common.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
> [3.x] temporarily move integritystatus to zonedef;

- src/scripts/quest/ManFst005.cpp
- src/scripts/quest/classquest/ARC/ClsArc000.cpp
- src/scripts/quest/classquest/ARC/ClsArc002.cpp
- ManFst005 not hiding UI during cutscene
- ClasArc002 missing step to progress to Quest Sequence 4
> Fixed bugs with some existing quests

- src/world/Manager/AchievementMgr.cpp
slightly broken for first item
> [3.x] add achv history support;

- src/common/Network/PacketDef/Ipcs.h
> Update ServerZoneIpcTypes for 6.35

- src/common/CommonGen.h
- src/common/Exd/ExdDataGenerated.cpp
- src/common/Exd/ExdDataGenerated.h
- src/tools/exd_common_gen/main.cpp
- src/world/Actor/PlayerInventory.cpp
- src/world/Territory/InstanceObjectCache.h
Excel changes were minor, but i had regenerated it anyway and it doesn't hurt.
> Fix building on gcc and regenerate exd for 6.35

- src/world/Actor/BNpc.cpp
- src/world/Actor/Player.cpp
- src/world/Territory/Cell.cpp
- src/world/Territory/Cell.h
- src/world/Territory/Territory.cpp
c7b50ca1e9172708d8658f3239d06c5efcbc404d
> Port cell update from master

- src/common/Common.h
- src/common/Network/PacketDef/Chat/ServerChatDef.h
- src/common/Network/PacketDef/Ipcs.h
- src/common/Network/PacketDef/Zone/ClientZoneDef.h
- src/common/Network/PacketDef/Zone/ServerZoneDef.h
- src/world/Actor/Player.cpp
- src/world/Actor/Player.h
- src/world/Manager/ChatChannelMgr.cpp
- src/world/Manager/ChatChannelMgr.h
- src/world/Manager/PartyMgr.cpp
- src/world/Manager/PartyMgr.h
- src/world/Network/GameConnection.cpp
- src/world/Network/GameConnection.h
- src/world/Network/Handlers/GMCommandHandlers.cpp
- src/world/Network/Handlers/PacketHandlers.cpp
- src/world/Network/Handlers/PartyHandlers.cpp
- src/world/Network/PacketWrappers/ChannelChatPacket.h
- src/world/Network/PacketWrappers/InviteHandlers.cpp
- src/world/Network/PacketWrappers/PartyUpdatePacket.h
- src/world/ServerMgr.cpp
- src/world/ServerMgr.h
- src/world/Session.cpp
This port does not handle offline players for now, they are removed from party when disconnect.
> [5.58]PartyMgr, ChatChannelMgr ported from 3.x

- src/common/Network/PacketDef/Ipcs.h
> Update for patch 6.41

- web/assets/js/github.js
- web/assets/js/login.js
- web/login.html
The JavaScript code has been moved to separate files: "assets/js/login.js" and "assets/js/github.js". Also, event listeners have been added to handle the login functionality and fetch recent activity from the GitHub API.
> Login.html refactored

- deps/datReader/bparse.h
- deps/datReaderPs3/bparse.h
- deps/mysqlConnector/ResultSetBase.h
- deps/mysqlConnector/mysql_util.h
- src/common/Crypt/base64.h
- src/world/Action/ActionResult.cpp
- web/login.html
Fixes clang compilation and reverts a commit on the launcher that made logging in impossible.
> [3.x] Fix clang compilation and launcher script

- web/assets/js/login.js
- web/createUser.html
- web/login.html
Depends on https://github.com/SapphireServer/SapphireLauncher/pull/26
> Pass lobbyPort to external.Boot

- src/world/Manager/PlayerMgr.cpp
There might have been a bug where you don't level up from exp at level 59 (it's fixed now if there was)
> Can now level up more than once from exp gain

- src/scripts/common/warptaxi/WarpInnGridania.cpp
currently the dialogue window for the Inn warps the player, even when the player hits cancel, or selects not to retire to the inn room. this adds a check and only warps the player if he selects to retire to the inn room. please disregard if fixed on a different branch
> fix WarpInnGridania to warp only on retire to room.
